<?php
/**
 * Created by PhpStorm.
 * User: viktorkafka
 * Date: 05/01/2018
 * Time: 10:59
 */

namespace App\Presenters;


use App\Forms\AdminFormFactory;
use App\Forms\UserFormFactory;
use App\Model\CategoryModel;
use App\Model\IngredientModel;
use App\Model\OrderModel;
use App\Model\ProductModel;
use App\Model\UserModel;
use App\Model\WalletModel;
use Nette\Application\AbortException;
use Nette\Application\UI\Form;
use Nette\Application\UI\Presenter;
use Nette\Http\FileUpload;
use Nette\Utils\DateTime;
use Nette\Utils\Image;
use Nette\Utils\Strings;
use V\Services\NotificationMail;

class AdminPresenter extends Presenter
{

    /**
     * @var AdminFormFactory
     * @inject
     */
    public $adminForm;

    /**
     * @var UserFormFactory
     * @inject
     */
    public $userForm;


    /**
     * @var UserModel
     *
     * @inject
     */
    public $userModel;

    /**
     * @var IngredientModel
     * @inject
     */
    public $ingredientModel;

    /**
     * @var ProductModel
     * @inject
     */
    public $productModel;

    /**
     * @var CategoryModel
     * @inject
     */
    public $categoryModel;

    /**
     * @persistent
     * @var
     */
    public $product_id;

    /**
     * @var WalletModel
     * @inject
     */
    public $walletModel;

    /**
     * @var
     * @persistent
     */
    public $date;

    /**
     * @var
     * @persistent
     */
    public $dateFrom;

    /**
     * @var
     * @persistent
     */
    public $dateTo;

    /**
     * @var
     * @persistent
     */
    public $userId;

    /**
     * @var OrderModel
     * @inject
     */
    public $orderModel;

    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
        $user = $this->userModel->getUserById($this->user->getId());
        if ($user->user_role_id != UserModel::USER_ROLE_ADMIN) {
            $this->flashMessage("Nemáte oprávnění.", "danger");
            $this->redirect("Homepage:default");
        }
    }

    protected function createComponentSignForNewsletter()
    {
        $form = $this->userForm->signForNewsletter();
        $form->onSuccess[] = [$this, 'signForNewsletterSucceeded'];
        return $form;
    }

    public function signForNewsletterSucceeded(Form $form)
    {
        $values = $form->getValues();
        try {
            $isSignedUp = $this->userModel->isEmailSignedForNewsletter($values->email);
            if ($isSignedUp) {
                throw new \Exception('Tento e-mail se již nachází v databázi pro odběr novinek');
            }
            $this->userModel->signForNewsletter($values->email);
            $this->flashMessage('Přihlášení k odběru proběhlo úspěšně.', 'success');
        } catch (\Exception $e) {
            $this->flashMessage($e->getMessage(), 'danger');
        }
    }

    protected function createComponentAddNewIngredientsForm()
    {
        $form = $this->adminForm->createNewIngredientsForm();
        $form->onSuccess[] = [$this, 'addNewIngredientSucceeded'];
        return $form;
    }

    public function addNewIngredientSucceeded(Form $form)
    {
        $values = $form->getValues();
        try {
            $this->ingredientModel->addIngredient($values);
            $this->flashMessage('Ingredience byla úspěšně vytvořena.', 'success');
            $this->redrawControl();
        } catch (\Exception $e) {
            $this->flashMessage($e->getMessage(), 'danger');
        }
    }


    public function handleDeleteIngredient($ingredientId)
    {
        try {
            $this->ingredientModel->removeIngredientFromAllProducts($ingredientId);
            $this->ingredientModel->removeIngredient($ingredientId);
            $this->flashMessage('Ingredience byla úspěšně smazána.', 'success');
            $this->redrawControl();
        } catch (\Exception $e) {
            $this->flashMessage($e->getMessage(), 'danger');
        }
    }

    public function renderDefault()
    {

    }

    public function renderIngredient()
    {
        $this->template->ingredients = $this->ingredientModel->getAllIngredients()->fetchAll();
    }

    public function renderProduct()
    {
        $this->template->products = $this->productModel->getAllProducts()->fetchAll();
    }

    public function renderCategory()
    {
        $this->template->categories = $this->categoryModel->getAllCategories();
    }

    public function renderProductDetail()
    {
        $this->template->productIngredients = $this->productModel->getProductIngredients($this->product_id)->fetchAll();
    }

    public function renderUsers()
    {
        $this->template->salatyUsers = $this->userModel->getAllUsers()->fetchAll();
    }

    public function renderOrdersDay()
    {
        if (empty($this->date)) {
            $date = new DateTime('+1 day');
            $this->date = $date->format('Y-m-d');
        }
        $this->template->date = new DateTime($this->date);
        $this->template->products = $this->orderModel->getProductOrdersByDate($this->date)->fetchAll();
        $this->template->ingredients = $this->orderModel->getProductIngredientsByDate($this->date)->fetchAll();
    }

    public function renderUserOrdersDay()
    {
        if (empty($this->date)) {
            $date = new DateTime('+1 day');
            $this->date = $date->format('Y-m-d');
        }
        $this->template->date = new DateTime($this->date);

        $this->template->usersWithProducts = $this->orderModel->getUsersOrdersByDate($this->date)->fetchAssoc('user_id[]');
        $this->template->usersWithOrders = $this->orderModel->getUsersOrdersByDate($this->date)->fetchAssoc('user_id');
    }

    public function renderOrdersTerm()
    {
        if (empty($this->dateFrom)) {
            $date = new DateTime('+1 day');
            $this->dateFrom = $date->format('Y-m-d');
        }
        if (empty($this->dateTo)) {
            $date = new DateTime('+2 day');
            $this->dateTo = $date->format('Y-m-d');
        }
        $this->template->dateFrom = new DateTime($this->dateFrom);
        $this->template->dateTo = new DateTime($this->dateTo);
        $this->template->products = $this->orderModel->getProductOrdersByTerm($this->dateFrom, $this->dateTo)->fetchAll();
        $this->template->ingredients = $this->orderModel->getProductIngredientsByTerm($this->dateFrom, $this->dateTo)->fetchAll();
    }

    public function renderWallet()
    {
        $users = $this->userModel->getAllUsers()->fetchAll();
        if (isset($users[0]) && empty($this->userId)) {
            $this->userId = $users[0]['id'];
        }
        $this->template->userWallet = $this->walletModel->getWalletByUser($this->userId)->fetchAll();
    }

    public function handleChangeUser()
    {
        $userId = $this->presenter->getRequest()->getPost('userId');
        $this->userId = $userId;
        $this->redrawControl();
    }

    protected function createComponentAddNewCategoryForm()
    {
        $form = $this->adminForm->createNewCategoryForm();
        $form->onSuccess[] = [$this, 'addNewCategorySucceeded'];
        return $form;
    }

    public function addNewCategorySucceeded(Form $form)
    {
        $values = $form->getValues();
        try {
            $this->categoryModel->addCategory($values);
            $this->flashMessage('Kategorie produktů byla úspěšně přidána.', 'success');
        } catch (\Exception $e) {
            $this->flashMessage($e->getMessage(), 'danger');
        }
    }

    public function handleActivateCategory($categoryId)
    {
        $this->categoryModel->changeCategoryState($categoryId, 1);
        $this->redrawControl();
    }

    public function handleDeactivateCategory($categoryId)
    {
        $this->categoryModel->changeCategoryState($categoryId, 0);
        $this->redrawControl();
    }

    public function handleChangeProductState($productId, $state)
    {
        $this->productModel->changeProductState($productId, $state);
        $this->redrawControl();
    }

    protected function createComponentEditProductForm()
    {
        $product = $this->productModel->getProduct($this->product_id);
        $form = $this->adminForm->createEditProduct($product);
        $form->onSuccess[] = [$this, 'editProduct'];
        return $form;
    }

    public function editProduct(Form $form)
    {
        $values = $form->getValues();
        try {
            $data = [
                'id' => $this->product_id,
                'name' => $values->name,
                'description' => $values->description,
                'price' => $values->price,
                'category_id' => $values->category_id,
                'weight' => $values->weight,
                'rank' => $values->rank,
            ];

            if ($values->img->isImage() && $values->img->isOk()) {
                $imgPath = '/data/products/' . date("Y-m-d-h-i-s") . "-" . $values->img->name;
                $thumbPath = '/data/products/thumb/' . date("Y-m-d-h-i-s") . "-" . $values->img->name;

                $this->formatImg($values->img, $imgPath, $thumbPath);
                $this->productModel->changeProductImg($imgPath, $this->product_id);
            }


            $ingredients = [];
            foreach ($values->ingredients as $ingredient) {
                $ingredients[$ingredient] = [
                    'product_id' => (int)$this->product_id,
                    'ingredient_id' => $ingredient,
                ];
            }

            $this->productModel->editProduct($data, $ingredients, $values->ingredients);

            $this->flashMessage('Editace proběhla úspěšně.', 'success');
        } catch (\Exception $e) {
            $this->flashMessage($e->getMessage(), 'danger');
        }

    }

    /**
     * Naformátování fotek na potřebné rozměry a vytvoření thumbu
     *
     * @param FileUpload $file
     * @param $imgPath
     * @param $thumbPath
     */
    public function formatImg(FileUpload $file, $imgPath, $thumbPath)
    {
        $path = WWW_DIR . $imgPath;
        $file->move($path);

        $image = Image::fromFile(WWW_DIR . $imgPath);
        /*    $image->resize(640, null);
            $image->resize(640, 480, Image::EXACT);
            $image->sharpen();*/
        $image->save(WWW_DIR . $imgPath);


        /*        $image->resize(160, 120, Image::EXACT);
                $image->sharpen();
                $image->save(WWW_DIR . $thumbPath);*/
    }

    protected function createComponentEditProductIngredientsForm()
    {
        $ingredients = $this->productModel->getProductIngredients($this->product_id)->fetchAll();
        $form = $this->adminForm->createEditProductIngredients($ingredients);
        $form->onSuccess[] = [$this, 'editProductIngredients'];
        return $form;
    }

    public function editProductIngredients(Form $form)
    {
        $values = $form->getValues();
        try {
            $this->productModel->editProductIngredients($values, $this->product_id);
            $this->flashMessage('Editace ingrediencí proběhla úspěšně.', 'success');
        } catch (\Exception $e) {
            $this->flashMessage($e->getMessage(), 'danger');
        }
    }

    protected function createComponentNewProductForm()
    {
        $form = $this->adminForm->createAddNewProduct();
        $form->onSuccess[] = [$this, 'addProduct'];
        return $form;
    }

    public function addProduct(Form $form)
    {
        $values = $form->getValues();
        try {
            if ($values->img->isImage() && $values->img->isOk()) {
                $imgPath = '/data/products/' . date("Y-m-d-h-i-s") . "-" . $values->img->name;
                $thumbPath = '/data/products/thumb/' . date("Y-m-d-h-i-s") . "-" . $values->img->name;

                $this->formatImg($values->img, $imgPath, $thumbPath);
                //$this->productModel->changeProductImg($imgPath, $this->product_id);
            }

            $data = [
                'name' => $values->name,
                'description' => $values->description,
                'img' => $imgPath,
                'price' => $values->price,
                'category_id' => $values->category_id,
                'weight' => $values->weight,
                'rank' => $values->rank,
            ];

            $this->productModel->addProduct($data, $values->ingredients);

        } catch (\Exception $e) {
            $this->flashMessage($e->getMessage(), 'danger');
        }
    }

    public function handleChangeUserStatus($userId, $status)
    {
        $user = $this->userModel->getUserById($userId);
        $this->userModel->changeUserStatus($userId, $status);
        if ($status == 1 && $user->active == 0) {
            $mail = new NotificationMail([], $user->email, NotificationMail::ACCOUNT_ACTIVATION, 'SalátyObe - Aktivace účtu');
            $mail->send();
        }
        $this->flashMessage('Změna proběhla úspěšně.', 'success');
    }

    protected function createComponentWallet()
    {
        $form = $this->adminForm->createWallet($this->userId);
        $form->onSuccess[] = [$this, 'walletSucceeded'];
        return $form;
    }

    public function walletSucceeded(Form $form)
    {
        $values = $form->getValues();
        $values['date'] = new DateTime();
        $values['filled_by_user_id'] = $this->user->getId();
        $this->walletModel->addMoney($values);
        $this->flashMessage('Přidání do peněženky proběhlo úspěšně.', 'success');
        $this->redirect('Admin:wallet');
    }

    protected function createComponentChangeDateForm()
    {
        $form = $this->adminForm->createChangeDate($this->date);
        $form->onSuccess[] = [$this, 'changeDateSucceeded'];

        return $form;
    }

    public function changeDateSucceeded(Form $form)
    {
        $values = $form->getValues();
        $this->date = $values->date;
        $this->redrawControl();
    }

    protected function createComponentChangeTermForm()
    {
        $form = $this->adminForm->createChangeTerm($this->dateFrom, $this->dateTo);
        $form->onSuccess[] = [$this, 'changeTermSucceeded'];

        return $form;
    }

    public function changeTermSucceeded(Form $form)
    {
        $values = $form->getValues();
        $this->dateFrom = $values->dateFrom;
        $this->dateTo = $values->dateTo;
        $this->redrawControl();
    }

    public function renderUserDetail()
    {
        $this->template->orders = $this->orderModel->getUserOrders($this->userId)->fetchAssoc('date[]');
    }
}